=== antoniocigales/sew/xml/etapa.dtd
<!-- ===================== ELEMENTO RAÍZ ===================== -->
<!ELEMENT etapa (nombreEtapa, numeroEtapa, longitudEtapa, fechaEtapa,
                 tiempoGanador, velocidadGanador, desnivelEtapa,
                 ciudadInicio, ciudadFinal,
                 referencias, multimedia,
                 lugarSalida, lugarLlegada,
                 hitosImportantes, clasificacion)>

<!-- ===================== DATOS GENERALES ===================== -->
<!ATTLIST etapa tipoEtapa  (llana|montaña|contrarreloj-individual|contrarreloj-por-equipos|media-montaña) #REQUIRED>
<!ELEMENT nombreEtapa      (#PCDATA)>
<!ELEMENT numeroEtapa      (#PCDATA)>

<!ELEMENT longitudEtapa    (#PCDATA)>
<!ATTLIST longitudEtapa    unidades  CDATA #REQUIRED>

<!ELEMENT fechaEtapa       (#PCDATA)>
<!ELEMENT tiempoGanador    (#PCDATA)>

<!ELEMENT velocidadGanador (#PCDATA)>
<!ATTLIST velocidadGanador unidades  CDATA #REQUIRED>

<!ELEMENT desnivelEtapa    (#PCDATA)>
<!-- OJO: en el XML el atributo está escrito "undidades" -->
<!ATTLIST desnivelEtapa    undidades CDATA #REQUIRED>

<!ELEMENT ciudadInicio     (#PCDATA)>
<!ELEMENT ciudadFinal      (#PCDATA)>


<!-- ===================== REFERENCIAS ===================== -->
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia  (#PCDATA)>

<!-- ===================== MULTIMEDIA ===================== -->
<!ELEMENT multimedia (fotos, videos, sonidos)>
<!ELEMENT fotos      (foto+)>
<!ELEMENT foto       (#PCDATA)>
<!ELEMENT videos     (video+)>
<!ELEMENT video      (#PCDATA)>
<!ELEMENT sonidos    (sonido+)>
<!ELEMENT sonido     (#PCDATA)>

<!-- ===================== COORDENADAS ===================== -->
<!ELEMENT lugarSalida  (longitud, latitud, altitud)>
<!ELEMENT lugarLlegada (longitud, latitud, altitud)>

<!ELEMENT longitud  (#PCDATA)>
<!ATTLIST longitud  unidades CDATA #REQUIRED>
<!ELEMENT latitud   (#PCDATA)>
<!ATTLIST latitud   unidades CDATA #REQUIRED>
<!ELEMENT altitud   (#PCDATA)>
<!ATTLIST altitud   unidades CDATA #REQUIRED>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>

<!-- ===================== HITOS IMPORTANTES ===================== -->
<!ELEMENT hitosImportantes (puertos, sprints)>

<!ELEMENT puertos       (puertoMontaña*)>
<!ELEMENT puertoMontaña (longitud, latitud, altitud, distancia)>
<!ATTLIST puertoMontaña categoria (1-Categoría | 2-Categoría | Categoría-Esoecial | Bonificados) #REQUIRED>

<!ELEMENT sprints          (sprintIntermedio, sprintBonificado)>
<!ELEMENT sprintIntermedio (longitud, latitud, altitud, distancia)>
<!ELEMENT sprintBonificado (longitud, latitud, altitud, distancia)>

<!-- ===================== CLASIFICACIONES ===================== -->
<!ELEMENT clasificacion (clasificacionEtapaIndiv,
                         clasificacionEtapaEquipo,
                         clasificacionGeneral)>

<!ELEMENT clasificacionEtapaIndiv (clasificado1, clasificado2, clasificado3)>
<!ELEMENT clasificado1 (#PCDATA)>
<!ATTLIST clasificado1 tiempo CDATA #IMPLIED>
<!ELEMENT clasificado2 (#PCDATA)>
<!ATTLIST clasificado2 tiempo CDATA #IMPLIED>
<!ELEMENT clasificado3 (#PCDATA)>
<!ATTLIST clasificado3 tiempo CDATA #IMPLIED>

<!ELEMENT clasificacionEtapaEquipo (clasificado1General, clasificado2General, clasificado3General)>
<!ELEMENT clasificado1General (#PCDATA)>
<!ATTLIST clasificado1General tiempo CDATA #IMPLIED>
<!ELEMENT clasificado2General (#PCDATA)>
<!ATTLIST clasificado2General tiempo CDATA #IMPLIED>
<!ELEMENT clasificado3General (#PCDATA)>
<!ATTLIST clasificado3General tiempo CDATA #IMPLIED>

<!ELEMENT clasificacionGeneral (Equipo1, Equipo2, Equipo3)>
<!ELEMENT Equipo1 (#PCDATA)>
<!ATTLIST Equipo1 tiempo CDATA #IMPLIED>
<!ELEMENT Equipo2 (#PCDATA)>
<!ATTLIST Equipo2 tiempo CDATA #IMPLIED>
<!ELEMENT Equipo3 (#PCDATA)>
<!ATTLIST Equipo3 tiempo CDATA #IMPLIED>

=== antoniocigales/sew/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
 <etapa tipoEtapa = "montaña">
        <nombreEtapa>Almuñécar a Loja</nombreEtapa>
        <numeroEtapa>13</numeroEtapa>
        <longitudEtapa unidades = "km">500</longitudEtapa>
        <fechaEtapa>20-8-2026</fechaEtapa>
        <tiempoGanador>2-50-25</tiempoGanador>
        <velocidadGanador unidades= "km/h">38</velocidadGanador>
        <desnivelEtapa undidades = "m">5000</desnivelEtapa>
        <ciudadInicio>Almuñécar</ciudadInicio>
        <ciudadFinal>Loja</ciudadFinal>
        


        <referencias>

          <referencia>ref1</referencia>
          <referencia>ref2</referencia>
          <referencia>ref3</referencia>

        </referencias>


        <multimedia>

          <fotos>

              <foto>foto1</foto>
              <foto>foto2</foto>
              <foto>foto3</foto>

          </fotos>

          <videos>

              <video>vid1</video>
              <video>vid2</video>
              <video>vid3</video>

          </videos>

          <sonidos>
             <sonido>sonid1</sonido>
             <sonido>sonid2</sonido>
             <sonido>sonid3</sonido>
          </sonidos>

        </multimedia>


        <lugarSalida>
           <longitud unidades= "grados">500</longitud>
           <latitud unidades= "grados">500</latitud>
           <altitud unidades = "m">500</altitud>
        </lugarSalida>

        <lugarLlegada>
           <longitud unidades= "grados">500</longitud>
           <latitud unidades= "grados">500</latitud>
           <altitud unidades = "m">500</altitud>
        </lugarLlegada>


        <hitosImportantes>
         
          <puertos>

            <puertoMontaña categoria = "1-Categoría">
               <longitud unidades= "grados">500</longitud>
               <latitud unidades= "grados">500</latitud>
               <altitud unidades = "m">500</altitud>
               <distancia unidades = "km">50</distancia>
            </puertoMontaña>

            <puertoMontaña categoria = "2-Categoría">
               <longitud unidades= "grados">500</longitud>
               <latitud unidades= "grados">500</latitud>
               <altitud unidades = "m">500</altitud>
               <distancia unidades = "km">50</distancia>
            </puertoMontaña>

          </puertos>

          <sprints>

            <sprintIntermedio>
              <longitud unidades= "grados">500</longitud>
              <latitud unidades= "grados">500</latitud>
              <altitud unidades = "m">500</altitud>
              <distancia unidades = "km">50</distancia>

            </sprintIntermedio>

            <sprintBonificado>
               <longitud unidades= "grados">500</longitud>
               <latitud unidades= "grados">500</latitud>
               <altitud unidades = "m">500</altitud>
               <distancia unidades = "km">50</distancia>

            </sprintBonificado>

          </sprints>

      </hitosImportantes>


        <clasificacion>

           <clasificacionEtapaIndiv>
             <clasificado1>Jonás</clasificado1>
             <clasificado2 tiempo = "50">Paco</clasificado2>
             <clasificado3 tiempo = "100">Manuel</clasificado3>
           </clasificacionEtapaIndiv>

           <clasificacionEtapaEquipo>
             <clasificado1General>Jonás</clasificado1General>
             <clasificado2General tiempo = "50">Paco</clasificado2General>
             <clasificado3General tiempo = "100">Manuel</clasificado3General>
          </clasificacionEtapaEquipo>

          <clasificacionGeneral>
            <Equipo1>Jonás</Equipo1>
            <Equipo2 tiempo = "50">Paco</Equipo2>
            <Equipo3 tiempo = "100">Manuel</Equipo3>
         </clasificacionGeneral>


        </clasificacion>
        

    </etapa>
